"""Register the Unitree H1-2 (+ Magpie hands) as a first-class robosuite robot.

Importing this module once (before ``robocasa.utils.env_utils.create_env`` /
``robosuite.make``) makes ``robots="H1_2"`` resolvable and installs the RoboCasa
placement patch so the full-legged humanoid is positioned by its pelvis free
joint (RoboCasa's stock path writes mobile-base joints that this robot lacks).

Assets live in ``CL_Assets/robosuite_assets`` (generated by
``CL_Assets/robosuite_assets/build_assets.py``). The robot keeps all 27 actuators
and its floating base; locomotion is driven externally by the ROS walking policy
over DDS — robosuite controllers are never stepped (we own ``mujoco.mj_step``).

NOTE: robosuite/robocasa import only inside the MuJoCo container (mujoco==3.3.1).
This module is syntax-valid on the host but must be exercised in the container.
The API here follows robosuite master / robocasa main as surveyed in the design
doc (docs/superpowers/specs/2026-06-08-robocasa-mujoco-eval-integration-design.md).
"""
import os

import numpy as np

from robosuite.models.grippers import register_gripper
from robosuite.models.grippers.gripper_model import GripperModel
from robosuite.models.robots.manipulators.legged_manipulator_model import (
    LeggedManipulatorModel,
)
from robosuite.robots import register_robot_class

# --------------------------------------------------------------------------- #
# Asset paths (resolve in both the container, /home/code/..., and on the host)
# --------------------------------------------------------------------------- #
_ASSETS = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "CL_Assets", "robosuite_assets")
)
ROBOT_XML = os.path.join(_ASSETS, "robots", "h1_2", "robot.xml")
GRIPPER_RIGHT_XML = os.path.join(_ASSETS, "grippers", "magpie_right_gripper.xml")
GRIPPER_LEFT_XML = os.path.join(_ASSETS, "grippers", "magpie_left_gripper.xml")

# Kept in sync with CL_Assets/robosuite_assets/build_assets.py. The DDS bridge
# uses this to translate ROS joint names -> sim (robosuite, robot0_-prefixed)
# joint names. Only the 12 legs are renamed; arms/torso are unchanged.
LEG_JOINT_RENAME = {
    f"{side}_{j}_joint": f"{side}_leg_{j}_joint"
    for side in ("left", "right")
    for j in ("hip_yaw", "hip_pitch", "hip_roll", "knee", "ankle_pitch", "ankle_roll")
}

# Free joint name on the pelvis (used by the placement patch).
FREE_JOINT_NAME = "floating_base_joint"

# Initial stance for the 27 actuated joints (excludes the 7-DoF free joint).
# Model-level init stays zeros, and the harness spawns at zeros too
# (h12_mujoco.sim_loop). NOMINAL_STANCE / nominal_stance_vector below stay
# available for an upright standing spawn but are not the default.
_INIT_QPOS = np.zeros(27)

# Nominal standing stance, keyed by ROS joint name. Legs are the walking policy's
# default_angles (core_ws/.../h12_lowerbody_controller/example/h1_2.yaml) so the
# stance matches what the policy will hold (clean handoff). Arms are tucked
# down/back (shoulder_pitch +1.0, elbow +0.3) so the hands clear the kitchen
# fixtures — at zeros the hands jut ~0.31 m forward into the counter. Everything
# unlisted is 0 (torso, wrists, shoulder roll/yaw).
NOMINAL_STANCE = {
    **{f"{s}_hip_pitch_joint": -0.16 for s in ("left", "right")},
    **{f"{s}_knee_joint": 0.36 for s in ("left", "right")},
    **{f"{s}_ankle_pitch_joint": -0.2 for s in ("left", "right")},
    **{f"{s}_shoulder_pitch_joint": 1.0 for s in ("left", "right")},
    **{f"{s}_elbow_joint": 0.3 for s in ("left", "right")},
}


def nominal_stance_vector():
    """The 27-vector of NOMINAL_STANCE angles ordered by sim_names.ROS_MOTOR_ORDER
    (== NameResolver.motor_qpos order). Not used by the default all-zero spawn;
    write data.qpos[resolver.motor_qpos] = nominal_stance_vector() for a standing
    pose."""
    from sim_names import ROS_MOTOR_ORDER

    return np.array([NOMINAL_STANCE.get(n, 0.0) for n in ROS_MOTOR_ORDER], dtype=float)


# --------------------------------------------------------------------------- #
# Grippers
# --------------------------------------------------------------------------- #
class _MagpieGripperBase(GripperModel):
    """Shared Magpie 4-bar parallel-jaw gripper behaviour.

    Two independently-actuated crank joints (finger_joint1/2) close the jaws via
    the in-XML <equality><connect> 4-bar linkage. We never call env.step(), so
    format_action is the identity and the controller is construction-only.
    """

    def format_action(self, action):
        return action

    @property
    def init_qpos(self):
        # Length == number of gripper joints in the MJCF (3 hinges x 2 fingers).
        return np.zeros(6)

    @property
    def speed(self):
        return 0.2

    @property
    def dof(self):
        return 2

    @property
    def _important_geoms(self):
        return {
            "left_finger": ["left_pad1", "left_pad2", "left_pad3", "left_pad4"],
            "right_finger": ["right_pad1", "right_pad2", "right_pad3", "right_pad4"],
            "left_fingerpad": ["left_pad4"],
            "right_fingerpad": ["right_pad4"],
        }


@register_gripper
class MagpieRightGripper(_MagpieGripperBase):
    def __init__(self, idn=0):
        super().__init__(GRIPPER_RIGHT_XML, idn=idn)


@register_gripper
class MagpieLeftGripper(_MagpieGripperBase):
    def __init__(self, idn=0):
        super().__init__(GRIPPER_LEFT_XML, idn=idn)


# --------------------------------------------------------------------------- #
# Robot model
# --------------------------------------------------------------------------- #
@register_robot_class("LeggedRobot")
class H1_2(LeggedManipulatorModel):
    """Full-legged Unitree H1-2 with two Magpie hands.

    Keeps the real pelvis free joint + all 27 actuators so the ROS walking policy
    and arm IK drive every joint over DDS, and the legs can locomote via floor
    contact. RoboCasa placement is redirected to the pelvis free joint by
    ``install_robocasa_patches()`` below.

    Base = ``NullBase`` (a ``NullBaseModel``), NOT ``NoActuationBase``: the latter
    is a ``MobileBaseModel`` and routes through ``add_mobile_base()``, which
    deletes the pelvis ``<freejoint>`` ("freejoints can only be used at top
    level") and rigidly welds the robot to a jointless ``mobilebase0`` — i.e.
    fixes the robot to the world. ``NullBase`` routes through ``add_null_base()``,
    which leaves the robot tree (and the freejoint) untouched, so the floating
    base survives and the robot can fall/step/balance under physics.
    """

    arms = ["right", "left"]

    def __init__(self, idn=0):
        super().__init__(ROBOT_XML, idn=idn)

    @property
    def default_base(self):
        return "NullBase"

    @property
    def default_gripper(self):
        return {"right": "MagpieRightGripper", "left": "MagpieLeftGripper"}

    @property
    def default_controller_config(self):
        # Abstract -> must exist, but effectively unused here: robosuite loads
        # controllers via load_composite_controller_config(robot="H1_2"), which
        # lowercases to "h1_2", finds no default_h1_2.json, and silently falls
        # back to the BASIC composite controller (no crash). We never call
        # env.step(), so the controller is construction-only and this value inert.
        return {"right": "default_h1", "left": "default_h1"}

    @property
    def init_qpos(self):
        return _INIT_QPOS

    @property
    def base_xpos_offset(self):
        return {
            "bins": (-0.5, -0.1, 0.0),
            "empty": (-0.29, 0, 0.0),
            "table": lambda table_length: (-0.26 - table_length / 2, 0, 0.0),
        }

    @property
    def top_offset(self):
        return np.array((0, 0, 1.0))

    @property
    def _horizontal_radius(self):
        return 0.5

    @property
    def arm_type(self):
        return "bimanual"

    @property
    def _eef_name(self):
        return {"right": "right_hand", "left": "left_hand"}


# --------------------------------------------------------------------------- #
# RoboCasa placement patch: position the full-legged humanoid by its pelvis free
# joint instead of the absent mobilebase0_joint_mobile_* joints.
# --------------------------------------------------------------------------- #
def place_robot_freejoint(env, pos, quat_wxyz):
    """Write the pelvis free joint qpos (xyz + wxyz quat) for an H1_2 env.

    Robust primitive usable directly from the eval harness regardless of whether
    the monkeypatch below matched the installed RoboCasa version.
    """
    sim = env.sim
    jname = f"{env.robots[0].robot_model.naming_prefix}{FREE_JOINT_NAME}"
    addr = sim.model.get_joint_qpos_addr(jname)
    start = addr[0] if isinstance(addr, tuple) else addr
    sim.data.qpos[start : start + 3] = np.asarray(pos, dtype=float)
    sim.data.qpos[start + 3 : start + 7] = np.asarray(quat_wxyz, dtype=float)
    sim.forward()


def lowest_robot_point_z(env, prefixes=("robot0_", "gripper0_")):
    """Min world-z over the robot's own geoms (not fixtures/floor), using each
    geom's tight AABB transformed to world. Bounding-sphere rbound is far too
    conservative for flat feet, so we use geom_aabb."""
    import mujoco

    m = env.sim.model._model
    d = env.sim.data._data
    corners = np.array(
        [[sx, sy, sz] for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)], dtype=float
    )
    best = float("inf")
    for i in range(m.ngeom):
        bn = mujoco.mj_id2name(m, mujoco.mjtObj.mjOBJ_BODY, m.geom_bodyid[i]) or ""
        if not bn.startswith(prefixes):
            continue
        aabb = m.geom_aabb[i]
        world = (corners * aabb[3:] + aabb[:3]) @ d.geom_xmat[i].reshape(3, 3).T + d.geom_xpos[i]
        best = min(best, float(world[:, 2].min()))
    return best


def place_robot_clear(env, pos, quat_wxyz, clearance=0.02):
    """Place the pelvis free joint, then lift so the lowest robot point clears the
    floor (z=0) by `clearance`. Robust to stance/init_qpos."""
    place_robot_freejoint(env, pos, quat_wxyz)  # writes pose + sim.forward()
    low = lowest_robot_point_z(env)
    if low != float("inf"):
        sim = env.sim
        jname = f"{env.robots[0].robot_model.naming_prefix}{FREE_JOINT_NAME}"
        addr = sim.model.get_joint_qpos_addr(jname)
        start = addr[0] if isinstance(addr, tuple) else addr
        sim.data.qpos[start + 2] += clearance - low
        sim.forward()


def _backward_dir(base_quat):
    """World-frame unit vector pointing 'backward' for a robot at orientation
    base_quat (wxyz). The robot faces +x in its own frame (toward the kitchen
    counter), so backward = -(local +x) rotated into the world, flattened to the
    floor plane and normalized. Falls back to -x if the rotated axis is vertical."""
    import mujoco

    fwd = np.zeros(3)
    mujoco.mju_rotVecQuat(fwd, np.array([1.0, 0.0, 0.0]), np.asarray(base_quat, dtype=float))
    back = -fwd
    back[2] = 0.0
    n = np.linalg.norm(back)
    return back / n if n > 1e-9 else np.array([-1.0, 0.0, 0.0])


def _robot_env_contacts(model, data, prefixes=("robot0_", "gripper0_")):
    """Penetrating contacts between a robot geom and a non-robot (environment)
    geom. 'Penetrating' = contact.dist < 0 (actual overlap, not merely within
    margin). Robot-vs-robot (self) and env-vs-env contacts are skipped — moving
    the base can't fix a self-collision. The floor is excluded implicitly:
    place_robot_clear keeps the robot above it, so it never penetrates."""
    import mujoco

    out = []
    for i in range(data.ncon):
        c = data.contact[i]
        if c.dist >= 0:
            continue
        b1 = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, model.geom_bodyid[c.geom1]) or ""
        b2 = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, model.geom_bodyid[c.geom2]) or ""
        if b1.startswith(prefixes) == b2.startswith(prefixes):
            continue  # both robot or both env -> not a robot<->env collision
        out.append(c)
    return out


def place_robot_collision_free(env, base_pos, base_quat, step=0.02, max_iters=25, clearance=0.02):
    """Place the robot collision-free at spawn by backing it away from whatever it
    overlaps.

    Starting from the RoboCasa placement (base_pos, base_quat wxyz), place the
    robot (place_robot_clear auto-fits floor clearance), then while any robot geom
    penetrates an environment geom, step the base backward (the robot's -x, away
    from the counter it faces) by `step` and retry, up to `max_iters` steps
    (default 25 x 2 cm = 0.5 m). Orientation never changes — pure translation.

    Tracks the least-penetrating position seen (fewest contacts, then least total
    depth). If still colliding after max_iters, restores that best position and
    warns (best-effort), so the sim still launches. Self-collisions at the zero
    pose are not addressed here — translation can't fix them."""
    back = _backward_dir(base_quat)
    model = env.sim.model._model
    data = env.sim.data._data
    pos = np.array(base_pos, dtype=float)
    best_pos, best_score = None, None
    for i in range(max_iters + 1):
        place_robot_clear(env, pos, base_quat, clearance)  # writes pose + z-fit + sim.forward()
        contacts = _robot_env_contacts(model, data)
        score = (len(contacts), sum(-c.dist for c in contacts))
        if best_score is None or score < best_score:
            best_score, best_pos = score, pos.copy()
        if not contacts:
            if i:
                print(f"[h1_2_robosuite] moved robot back {i * step:.2f} m to clear spawn collision")
            return
        pos[:2] += step * back[:2]
    place_robot_clear(env, best_pos, base_quat, clearance)  # restore least-penetrating try
    print(f"[h1_2_robosuite] WARNING: spawn still in collision after backing off "
          f"{max_iters * step:.2f} m; keeping best position "
          f"({best_score[0]} contact(s), {best_score[1]:.3f} m penetration)")


_PATCHED = False


def _euler_to_wxyz(euler):
    """RoboCasa base orientation -> wxyz quat. Accepts euler [roll,pitch,yaw],
    a yaw scalar, or an existing wxyz quat. RoboCasa stores init_robot_base_ori
    as a 3-vector euler (typically [0,0,yaw])."""
    if euler is None:
        return np.array([1.0, 0.0, 0.0, 0.0])
    e = np.asarray(euler, dtype=float).reshape(-1)
    if e.size == 4:
        return e
    if e.size == 1:
        e = np.array([0.0, 0.0, float(e[0])])
    r, p, y = e[0], e[1], e[2]
    cr, sr = np.cos(r / 2), np.sin(r / 2)
    cp, sp = np.cos(p / 2), np.sin(p / 2)
    cy, sy = np.cos(y / 2), np.sin(y / 2)
    return np.array([
        cr * cp * cy + sr * sp * sy,
        sr * cp * cy - cr * sp * sy,
        cr * sp * cy + sr * cp * sy,
        cr * cp * sy - sr * sp * cy,
    ])


def install_robocasa_patches():
    """Redirect RoboCasa base placement to the pelvis free joint for H1_2.

    RoboCasa's Kitchen._reset_internal positions the robot two ways and BOTH
    raise for our NoActuationBase + freejoint robot (they write the absent
    mobilebase0_joint_mobile_* joints):
      * fresh/random branch: EnvUtils.set_robot_base(env=..., anchor_pos=...,
        anchor_ori=..., ...) -> returns robot_pos, which kitchen stores.
      * cached (ep_meta) branch: EnvUtils.set_robot_to_position(env, global_pos).
    We fully short-circuit both for H1_2 (never call the originals, which would
    KeyError) and write the free joint instead. Non-H1_2 robots are untouched.
    Note set_robot_base internally calls the module-global set_robot_to_position,
    so short-circuiting set_robot_base (not falling through) is required.
    """
    global _PATCHED
    if _PATCHED:
        return
    import warnings

    try:
        from robocasa.utils import env_utils as EU
    except Exception as e:  # pragma: no cover - container only
        warnings.warn(f"[h1_2_robosuite] robocasa not importable: {e}")
        return

    # Placement z-offset so the standing pelvis doesn't sink. 1.05 keeps the feet
    # ~1 cm clear at init_qpos=0 (foot sole sits at pelvis_z - 1.041); the harness
    # additionally auto-fits clearance after reset via place_robot_clear().
    offsets = getattr(EU, "_ROBOT_POS_OFFSETS", None)
    if isinstance(offsets, dict):
        offsets.setdefault("H1_2", [0.0, 0.0, 1.05])

    def _is_h1_2(env):
        try:
            return type(env.robots[0].robot_model).__name__ == "H1_2"
        except Exception:
            return False

    orig_set_base = getattr(EU, "set_robot_base", None)
    orig_set_pos = getattr(EU, "set_robot_to_position", None)

    if orig_set_base is not None:
        def set_robot_base(*args, **kwargs):
            env = kwargs.get("env", args[0] if args else None)
            if env is not None and _is_h1_2(env):
                anchor_pos = kwargs.get("anchor_pos", args[1] if len(args) > 1 else None)
                anchor_ori = kwargs.get("anchor_ori", args[2] if len(args) > 2 else None)
                pos = np.array(anchor_pos, dtype=float) if anchor_pos is not None else np.zeros(3)
                env.init_robot_base_pos = pos
                env.init_robot_base_ori = (
                    np.array(anchor_ori, dtype=float) if anchor_ori is not None else np.zeros(3)
                )
                place_robot_freejoint(env, pos, _euler_to_wxyz(anchor_ori))
                return pos  # kitchen does: self.init_robot_base_pos = <return value>
            return orig_set_base(*args, **kwargs)

        EU.set_robot_base = set_robot_base

    if orig_set_pos is not None:
        def set_robot_to_position(*args, **kwargs):
            env = kwargs.get("env", args[0] if args else None)
            global_pos = kwargs.get("global_pos", args[1] if len(args) > 1 else None)
            if env is not None and _is_h1_2(env) and global_pos is not None:
                ori = getattr(env, "init_robot_base_ori", None)
                place_robot_freejoint(env, np.array(global_pos, dtype=float), _euler_to_wxyz(ori))
                return
            return orig_set_pos(*args, **kwargs)

        EU.set_robot_to_position = set_robot_to_position

    if orig_set_base is None and orig_set_pos is None:
        warnings.warn(
            "[h1_2_robosuite] no RoboCasa placement entry point found to patch; "
            "call place_robot_freejoint(env, pos, quat) from the harness after reset."
        )
    _PATCHED = True


# --------------------------------------------------------------------------- #
# Convenience env constructor
# --------------------------------------------------------------------------- #
def make_kitchen_env(env_name, layout_ids=None, style_ids=None, seed=None, **kwargs):
    """Build a RoboCasa kitchen task env with robots='H1_2', headless and without
    camera observations.

    We bypass robocasa.utils.env_utils.create_env on purpose: it hard-codes
    has_offscreen_renderer=True, use_camera_obs=True and agentview camera_names
    (merged inline via **kwargs, so they can't be overridden), and robosuite's
    reset() unconditionally calls initialize_renderer() which then fails on the
    missing agentview cameras. We own visualization (mujoco.viewer) and read env
    state directly, so we disable robosuite's renderer + camera obs entirely.

    The Kitchen task classes are registered in robosuite.REGISTERED_ENVS by
    robocasa's metaclass (on `import robocasa`, triggered by
    install_robocasa_patches), so robosuite.make resolves the task by name. With
    controller_configs omitted, the robot falls back to the BASIC composite
    controller (construction-only; never stepped).

    Returns the env; the caller drives env.sim's raw MjModel/MjData with the
    custom mj_step loop and reads env._check_success()/reward()/get_ep_meta().
    """
    install_robocasa_patches()  # also triggers `import robocasa` -> env registration
    import robocasa  # noqa: F401  (ensure Kitchen envs are registered)
    import robosuite

    env_kwargs = dict(
        env_name=env_name,
        robots="H1_2",
        has_renderer=False,
        has_offscreen_renderer=False,
        use_camera_obs=False,
        use_object_obs=True,
        render_camera=None,   # base.py skips camera_name2id(...) when None
        ignore_done=True,
    )
    for k, v in (("layout_ids", layout_ids), ("style_ids", style_ids), ("seed", seed)):
        if v is not None:
            env_kwargs[k] = v
    env_kwargs.update(kwargs)
    return robosuite.make(**env_kwargs)
